Repository open-cluster-management-io/open-cluster-management-io.github.io, pull requests merged in 2021-06, with the labels that each got.

#79 add blog section and blog entries to website
  content/_index.md
  content/blog/_index.md
  content/blog/blog.md
Labels: approved, dco-signoff: yes, lgtm

#82 fix deploy app sub to managed cluster instruction
  content/getting-started/integration/app-lifecycle.md
Labels: approved, dco-signoff: yes, lgtm

#81 Add clusteradm
  content/clusteradm.md
  layouts/_default/clusteradm.html
  layouts/sitemap.xml
Labels: approved, dco-signoff: yes, lgtm

#84 Change cname
  deploy.sh
Labels: approved

#86 fixed link for quick start and re-enable edit button
  config.toml
  content/getting-started/quick-start/_index.md
Labels: approved, lgtm

#91 Add 'gurnben' to owners for website maintenance
  OWNERS
Labels: approved, lgtm

#92 align website with accelerated cncf submission proposal
  content/_index.md
  content/getting-started/integration/_index.md
  content/getting-started/integration/app-lifecycle.md
  content/getting-started/integration/policy-controllers.md
  content/getting-started/integration/policy-framework.md
  themes/hugo-geekdoc/layouts/partials/site-footer.html
Labels: approved, lgtm

#85 Update readme
  .github/workflows/postsubmit.yml
  .github/workflows/presubmit.yml
  README.md
Labels: approved, lgtm

#95 fix deploy website
  Makefile
  deploy.sh
Labels: approved, lgtm

#93 Correct wrong env/cli in klusterlet agent installation
  content/getting-started/core/register-cluster.md
Labels: approved, lgtm

#90 Add clusteradm instruction
  content/getting-started/quick-start/_index.md
Labels: approved, lgtm

#96 fix deploy
  Makefile
  deploy.sh
Labels: approved, lgtm

#98 re-enable applifecycle steps
  content/_index.md
  content/getting-started/integration/_index.md
  content/getting-started/integration/app-lifecycle.md
Labels: approved, lgtm

#94 Add api design.md
  content/concepts/addon.md
  content/concepts/architecture.md
  content/concepts/managedcluster.md
  content/concepts/manifestwork.md
  content/concepts/placement.md
Labels: approved, lgtm

#97 fix core link in quick start page and added clusteradm init on front page
  content/_index.md
  content/getting-started/quick-start/_index.md
  static/clusteradm_init.png
Labels: approved, lgtm

#99 Add placement design
  content/concepts/addon.md
  content/concepts/managedcluster.md
  content/concepts/manifestwork.md
  content/concepts/placement.md
Labels: approved, lgtm

#100 fix base url
  config.toml
Labels: approved, lgtm

#101 point roadmap to github project
  content/concepts/roadmap.md
Labels: approved, lgtm

#103 add release page
  content/_index.md
  content/community/releases.md
Labels: approved, lgtm

#105 adjust release cycle
  content/community/releases.md
Labels: approved, lgtm

#102 Update _index.md
  content/getting-started/quick-start/_index.md
Labels: approved, lgtm

#106 Add addon-framework goref
  content/addon-framework.md
  layouts/_default/addon-framework.html
  layouts/sitemap.xml
Labels: approved, lgtm
